services:
  postgres:
    image: postgres:17-alpine
    container_name: scheduling-service-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U scheduling-service -d scheduling-service" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - scheduling-service-network

#  scheduling-service-api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: scheduling-service
#    env_file:
#      - .env
#    ports:
#      - "8080:8080"
#    depends_on:
#      postgres:
#        condition: service_healthy
#    networks:
#      - scheduling-service-network
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: scheduling-service-zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - scheduling-service-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: scheduling-service-kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - scheduling-service-network

  kafka-init-topics:
    image: confluentinc/cp-kafka:7.5.0
    container_name: scheduling-service-kafka-init-topics
    depends_on:
      - kafka
    command: >
      bash -c "
        echo 'Waiting Kafka to be ready...'
        cub kafka-ready -b kafka:29092 1 30
        echo 'Creating topics...'
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic scheduling.appointment.notification --partitions 1 --replication-factor 1
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic scheduling.appointment.scheduled --partitions 1 --replication-factor 1
        echo 'Topics created successfully.'
      "
    networks:
      - scheduling-service-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: scheduling-service-kafka-ui
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - scheduling-service-network

volumes:
  postgres_data:
    driver: local

networks:
  scheduling-service-network:
    driver: bridge
