spring:
  application:
    name: api
  datasource:
    url: ${DB_HOST:jdbc:postgresql://localhost:5432/scheduling-service}
    username: ${DB_USERNAME:scheduling-service}
    password: ${DB_PASSWORD:scheduling-service-pwd}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
        default_schema: scheduling-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  flyway:
    enabled: true
    default-schema: scheduling-service
    schemas: scheduling-service
    locations: classpath:db/migration
    baseline-on-migrate: false

app:
  kafka:
    source-service: scheduling-service
    topics:
      notification: scheduling.appointment.notification
      appointment-scheduled: scheduling.appointment.scheduled

springdoc:
  api-docs:
    path: /v3/api-docs
    groups:
      enabled: true
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    enabled: true
  show-actuator: false
  enable-native-support: true
  use-management-port: false
  cache:
    disabled: false
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
