create table appointments (
    id bigint generated by default as identity primary key,
    uuid uuid not null unique,
    patient_id uuid not null,
    doctor_id uuid not null,
    appointment_date_time timestamp with time zone not null,
    status varchar(32) not null,
    deleted_at timestamp with time zone null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create index idx_appointments_uuid on appointments (uuid);
